version: 2

models:
  - name: stg_local_bike__brands
    description: "This model contains information about brand."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "Name of each brand."