version: 2

sources:
  - name: local_bike
    schema: final_project_databird_ae
    tables:
      - name: brands
      - name: categories
      - name: customer
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores